python main.py \
    --checkpoint-path ./checkpoints/ \
    --pretrained-path ./saved_models/ \
    --images-path ./data/train/train/ \
    --masks-path ./data/train_gt/train_gt/ \
    --num-epochs 1 \
    --lr 2e-4 \
    --batch-size 4 \
    --display-step 10 \
